---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: microservices-cluster
  region: us-east-1

managedNodeGroups:
  - name: ng1-encrypt-using-default-kms-key
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true

  - name: ng2-encrypt-using-customer-encryption-key
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true